# Generated by Django 5.0.1 on 2024-02-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.FileField(blank=True, upload_to='articles_images/'),
        ),
    ]
