# Generated by Django 5.0.2 on 2024-02-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='articles',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='articles_images/'),
        ),
    ]
