# Generated by Django 5.0.2 on 2024-02-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
